### ISSUE TITLE
Dialogs in Multi-page contexts are broken

### ISSUE THREAD

**Issue by nvahalik** [opitzconsulting/jquery-mobile-angular-adapter#105]
See: http://jsfiddle.net/nvahalik/Am25V/

It routes correctly for just a moment and then flashes away.

**Comment by tbosch** [comment]
Hi,
this is due to the `otherwise` routing rule. If you remove this, it works as expected, see here: http://jsfiddle.net/Am25V/7/
I added a rule for `/` so you still have the redirect to your main page if the app is started.

The reason behind this that during dialogs the adapter redirects to a special url `&ui-state=dialog`. The handling for this special url is implemented in the default routing of the adapter.
So I think you are right that this is a bug in the adapter, so that the adapter still allows a custom default routing.

Thanks for reporting,
Tobias

**Comment by tbosch** [comment]
This is working with version 1.2.1-SNAPSHOT, see this fiddle: http://jsfiddle.net/Am25V/8/

Tobias
