### ISSUE TITLE
route system

### ISSUE THREAD

**Issue by mrbubbaz** [opitzconsulting/jquery-mobile-angular-adapter#106]
hello,
I'm trying to use the angular routing system but i got some issue.
If i put "#/somePage" link browser send it correctly but javascript trow "#%2FsomePage" so the link doesn't work.
Using angular by itself it anything work perfectly so I think that the problem is related to the adapter.
Any idea?

**Comment by tbosch** [comment]
Hi, 
could you provide a jsfiddle (or http://plnkr.co if you have external jquery mobile pages)? Try using `<a href="somePage">` instead of `<a href="#/somePage">`. The differences between plain angular and using the adapter might also be due to the fact that the adapter is enabling angular's html5 mode implicitly. 

Tobias

**Comment by mrbubbaz** [comment]
http://plnkr.co/edit/MZSSgnkhMSmWi7cyBeyI
using your workaround it seams to work but when i try to refresh the page it put me back to the first page because the browser have not upgrade the url.

**Comment by tbosch** [comment]
Hi, 
the normal preview link from plunkr.co uses an iframe for the app, so when you refresh the page everything will be reseted, no matter what url is loaded in the iframe.

For testing you plunk without the iframe, use the following url: http://run.plnkr.co/plunks/MZSSgnkhMSmWi7cyBeyI/

Tobias

By the way: Your "back" button does not work, as you uses the wrong markup. Instead of 

```
<a href="{{$location.goBack()}}" data-role="button"  data-theme="b"  data-icon="back" >Back to Index</a> 
```

Use

```
<a href="" data-rel="back" data-role="button"  data-theme="b"  data-icon="back" >Back to Index</a> 
```

So far, everything works as expected. If you don't have further problems I would close this issue.

**Comment by tbosch** [comment]
Closing this.
Feel free to reopen if you have other problems.

Tobias
