### ISSUE TITLE
ngm-vclick not firing when a is inside of a listview

### ISSUE THREAD

**Issue by nvahalik** [opitzconsulting/jquery-mobile-angular-adapter#109]
See: http://jsfiddle.net/nvahalik/SeVJA/

I'm trying to use ngm-vclick as part of a list view, but the event doesn't fire.  After RTFM, this doesn't appear to be completely unsupported... is there a better way or is this a bug?

**Comment by tbosch** [comment]
Hi,
well, the problem were the double curly braces within the `ngm-click`. You can refer to angular variables directly, e.g. `<a ngm-vclick="doSomething(device.id);">` instead of your `<a ngm-vclick="doSomething({{device.id}});">` 

Here is an updated fiddle:
http://jsfiddle.net/SeVJA/2/

Closing this...
Tobias

**Comment by nvahalik** [comment]
![Paris_Tuileries_Garden_Facepalm_statue](https://f.cloud.github.com/assets/632120/71259/ce43e26a-5fdf-11e2-8415-8a004822feec.jpg)

**Comment by tbosch** [comment]
+1!
