### ISSUE TITLE
Duplicated items from an angular list

### ISSUE THREAD

**Issue by martindevans** [opitzconsulting/jquery-mobile-angular-adapter#37]
As you can see from this [demo](http://placeholder-software.co.uk/jqm-bug/test.html) I put together, the two items in the controller list are displayed 4 times in the table created from an ng-repeat directive.

This is using the latest precompiled version (jquery-mobile-angular-adapter-standalone-1.0.7-rc3-SNAPSHOT.js), since I don't have everything set up to build myself.

**Comment by tbosch** [comment]
Hi, 
the problem is that you use the "standalone" version of the adapter. This includes jquery, jquery mobile, angular and the adapter in one file.
As you are including jquery, jquery mobile and angular separately, everything is doubled.

So, either use the standalone version of the adapter and remove the script-tags for jquery, jquery mobile and angular from your head-tag, or use the normal version of the adapter (without the "standalone" in it's name).

If you have any other problems, just let me know!

Tobias

**Comment by martindevans** [comment]
Doh! I suspected I was just doing something stupid, thanks :)
