### ISSUE TITLE
ngm-event throwing compile errors

### ISSUE THREAD

**Issue by johnlindquist** [opitzconsulting/jquery-mobile-angular-adapter#40]
http://jsfiddle.net/UF3dv/

Throws a "SyntaxError: Unexpected token c"

I haven't been able to get any syntax for ngm-event working.

**Comment by tbosch** [comment]
Hi,
yes, you are right, this is broken. Somehow the unit-test for this got dropped during the last redesign, sorry :-)
Thanks for reporting!

However, if you use the directive ngm-click instead of ngm-event it works. Those ngm-\* directives exist for all jquery mobile events:
http://jsfiddle.net/UF3dv/1/

Tobias

**Comment by johnlindquist** [comment]
Ok, I was trying to handle a <select> "change" event and didn't see ngm-change listed on the project README.

**Comment by tbosch** [comment]
Oh I see.
Please note: the ngm-\* directives are only made for the mobile specific events mentioned in the README. So ngm-change does not work, but ng-change should.

For all the other events please use the default angular directives. 
The only overlap is ngm-click and ng-click: However, ngm-click binds to "vclick" from jquery mobile, which is essentially a touchdown und touchup. So this is faster as a ng-click, as the real "click" is fired not until 200ms in mobile browsers. 

Tobias
