### ISSUE TITLE
collapsedSetter is not a function 

### ISSUE THREAD

**Issue by pdorgambide** [opitzconsulting/jquery-mobile-angular-adapter#67]
Into my page exist a collapsible-set with several collapsible.. the second one must be opened by default. (data-collapsed="false"). The librariy throws "collapsedSetter is not a function"

"div data-role="collapsible-set">
    div data-role="collapsible">
            Some Content
       /div>
      div data-role="collapsible" data-collapsed="false">
     /div>
      div data-role="collapsible" >
     /div>
/div>"

If remove the data-collapsed="false" attr it works fine. 
I hope that my short explanation could help you to locate and fix tehe problem.

Congratulations for your great and fantastic job,

**Comment by tbosch** [comment]
Hi,
here is a jsfiddle for reproducing this: http://jsfiddle.net/ZHKBA/31/

However, a collapsible requires a header and a content. If you insert a heading and a paragraph into every collapsible, it works fine. See here: http://jsfiddle.net/ZHKBA/30/

So the real problem is that your markup is erroneous :-(

Plain jquery mobile will just not display such collapsibles. I will change the adapter that it behaves the same way: If the markup is not right, just do nothing.

Thanks for reporting!
Tobias

**Comment by pdorgambide** [comment]
Hi,
Thanks for your answer and my apologies for reporting this erroneous markup.
I think that you are right in protect your code like jqm does to avoid throw the exception.

Again congratulations for your great job.
Pablo.

**Comment by tbosch** [comment]
This issue still exists, see here: http://jsfiddle.net/ESC98/
I will fix this soon!

**Comment by tbosch** [comment]
Here is an updated jsfiddle: http://jsfiddle.net/ESC98/1/ that uses 1.1.2-SNAPSHOT.
