### ISSUE TITLE
$navigate from a dialog breaks navigation

### ISSUE THREAD

**Issue by mlegenhausen** [opitzconsulting/jquery-mobile-angular-adapter#88]
Fiddle: http://jsfiddle.net/E8h48/2/

Click on `Next`. In the dialog again `Next`. When you now try to reopen the dialog you get an exception and the dialog can not be reopened.

Tobias, I hope you don't give up ;)

**Comment by tbosch** [comment]
Hi,
the exception is gone, but the reopening does not work. 
The reason is that I don't remove the `&ui-state=dialog` from the url when navigating from within a dialog, so this leads to an url of `http://jsfiddle.net/E8h48/2/show/&ui-state=dialog#main1` in the end of the example.

Your test cases are great, keep them coming!
Tobias

**Comment by tbosch** [comment]
Here is an updated jsfiddle: http://jsfiddle.net/E8h48/5/
Please note: The `$navigate` service is gone, see the Changelog.md for a migration guide.

Tobias
